### ISSUE TITLE
Test cases?

### ISSUE THREAD

**Issue by MichaelCombs28** [jdelic/12factor-vault#5]
Are there any test cases written for this project?

Do you have plans to integrate with a CI like travis?

**Comment by jdelic** [comment]
> Are there any test cases written for this project?

Short answer: no.

> Do you have plans to integrate with a CI like travis?

Short answer: someday

Long answer:
I am embarrassed by the lack of test coverage in this project, but I have a lot of things on my plate and it's working reliably for me in production, so writing those tests is relatively low on my list of priorities. I have a rough idea of what it would take to actually write integration tests, which will involve running a Vault in `-dev` mode, or initializing one using [this abomination of a bash script that I use to initialize Vault from Saltstack](https://github.com/jdelic/saltshaker/blob/master/srv/salt/vault/init.sls#L177-L200) and then [getting a database in there](https://docs.travis-ci.com/user/database-setup/) and then probably run [the most efficient Django test](https://blog.doismellburning.co.uk/the-most-efficient-django-test/) twice and wait 5 seconds between requests. Then run all of this through `tox` to test against Django 1.11 and 2.0.

Something like that.

So yeah... someday ;)

But feel free to submit a PR.
